### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by francepack** [JWoltjen/mod_0_skills#1]
@JWoltjen 
You performed well enough on the assessment to merit a chance to make some changes that can promote you to technical ready. Please make the following updates in your class_1.txt and class_2.txt files by EOD Sunday:

- [x] Attributes won't have special characters like '?' in their name, so you can remove those. I like how you are thinking about boolean variable names though.

- [x] Methods `newCustomer` and `newOrder` could use an active word at the beginning of the name to read like your other methods.

- [x] When writing out class names, you'll see a convention called PascalCase used across different coding languages. Just a slight change to class name 1 will make your name follow that convention!

**Comment by JWoltjen** [comment]
Thanks Mason, I cleared up those issues and pushed the changes. Let me know if I can do anything else!
